/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import merc.Classes.ClienteClasse;
import merc.Classes.EnderecoClasse;
import merc.Classes.FornecedorClasse;
import merc.controller.ClienteController;
import merc.controller.EnderecoClienteController;
import merc.controller.EnderecoController;
import merc.controller.FornecedorController;

/**
 *
 * @author bsbru
 */
public class ClientesEdit extends javax.swing.JFrame {
    
    
   public  ClienteClasse clientes;

    /**
     * Creates new form UsuariosAdd
     */
    public ClientesEdit(ClienteClasse cliente) {
        initComponents();
        
        clienteNomeEdit.setText(cliente.getNome());
        ClienteEmailEdit.setText(cliente.getE_mail());
        clienteTelefoneEdit.setText(cliente.getTelefone());
        clienteCpfEdit.setText(cliente.getCpf());
        clienteEnderecoEdit.setText(cliente.getEndereco());
        clienteCepEdit.setText(cliente.getCep());
        
        
        
        
        this.clientes = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeEditLabel = new javax.swing.JLabel();
        clienteNomeEdit = new javax.swing.JFormattedTextField();
        cepEditLabel = new javax.swing.JLabel();
        ClienteEmailEdit = new javax.swing.JFormattedTextField();
        clienteEditSave = new javax.swing.JButton();
        clienteTelefoneTelefoneLabel = new javax.swing.JLabel();
        clienteTelefoneEdit = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        clienteCepEdit = new javax.swing.JFormattedTextField();
        clienteEnderecoEdit = new javax.swing.JFormattedTextField();
        clienteCpfEditLabel = new javax.swing.JLabel();
        clienteCpfEdit = new javax.swing.JFormattedTextField();
        clienteCepEditLabel = new javax.swing.JLabel();
        clienteEnderecoEditLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        jLabel1.setText("Alterar Cliente");

        nomeEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nomeEditLabel.setText("Nome:");

        clienteNomeEdit.setToolTipText("");
        clienteNomeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteNomeEditActionPerformed(evt);
            }
        });

        cepEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cepEditLabel.setText("Email:");

        ClienteEmailEdit.setToolTipText("");
        ClienteEmailEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteEmailEditActionPerformed(evt);
            }
        });

        clienteEditSave.setText("Salvar");
        clienteEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEditSaveActionPerformed(evt);
            }
        });

        clienteTelefoneTelefoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteTelefoneTelefoneLabel.setText("Telefone:");

        clienteTelefoneEdit.setToolTipText("");
        clienteTelefoneEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTelefoneEditActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Endereço");

        clienteCepEdit.setToolTipText("");
        clienteCepEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCepEditActionPerformed(evt);
            }
        });

        clienteEnderecoEdit.setToolTipText("");
        clienteEnderecoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEnderecoEditActionPerformed(evt);
            }
        });

        clienteCpfEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteCpfEditLabel.setText("CPF:");

        clienteCpfEdit.setToolTipText("");
        clienteCpfEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCpfEditActionPerformed(evt);
            }
        });

        clienteCepEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteCepEditLabel.setText("CEP:");

        clienteEnderecoEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteEnderecoEditLabel.setText("Endereço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(clienteEditSave))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(131, 131, 131))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clienteCpfEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(clienteNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(clienteEnderecoEditLabel)
                                                .addComponent(clienteCepEditLabel))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(clienteEnderecoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(clienteCepEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(ClienteEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clienteTelefoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nomeEditLabel)
                                .addComponent(clienteTelefoneTelefoneLabel)
                                .addComponent(clienteCpfEditLabel)
                                .addComponent(cepEditLabel))
                            .addGap(410, 410, 410))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEditLabel)
                    .addComponent(clienteNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepEditLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteTelefoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteTelefoneTelefoneLabel))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteCpfEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteCpfEditLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteEnderecoEditLabel)
                    .addComponent(clienteEnderecoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteCepEditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteCepEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clienteEditSave)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void limpaTela(java.awt.event.ActionEvent evt){
        
        clienteNomeEdit.setText("");
        ClienteEmailEdit.setText("");
        clienteTelefoneEdit.setText("");
        clienteCpfEdit.setText("");
        clienteEnderecoEdit.setText("");
        clienteCepEdit.setText("");
        
    }
    
    private void atualizaTela(java.awt.event.ActionEvent evt){
        
    
        clienteNomeEdit.setText(this.clientes.getNome());
        ClienteEmailEdit.setText(this.clientes.getE_mail());
        clienteTelefoneEdit.setText(this.clientes.getTelefone());
        clienteCpfEdit.setText(this.clientes.getCpf());
        clienteEnderecoEdit.setText(this.clientes.getEndereco());
        clienteCepEdit.setText(this.clientes.getCep());

        
        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        this.dispose();
        
        
        ClienteController clienteController = new ClienteController();
        ArrayList<ClienteClasse> carregaClientes = clienteController.select();



        Clientes telaClientes = new Clientes(carregaClientes);
  
        telaClientes.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Clientes.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void clienteEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEditSaveActionPerformed
        // TODO add your handling code here:    
        
         if(clienteNomeEdit.getText().isEmpty()|| 
            ClienteEmailEdit.getText().isEmpty()||
            clienteTelefoneEdit.getText().isEmpty()||
            clienteEnderecoEdit.getText().isEmpty()||  
            clienteCpfEdit.getText().isEmpty()||
            clienteCepEdit.getText().isEmpty()                             
                 ){
           JOptionPane.showMessageDialog(null, "Dados incompletos!");
           return;
            
        }

        
        this.clientes.setNome(clienteNomeEdit.getText());
        this.clientes.setE_mail(ClienteEmailEdit.getText());
        this.clientes.setCpf(clienteCpfEdit.getText());
        this.clientes.setTelefone(clienteTelefoneEdit.getText());
        this.clientes.setEndereco(clienteEnderecoEdit.getText());
        this.clientes.setCep(clienteCepEdit.getText());
        
        System.out.println(this.clientes.getEndereco_id());
        
          
        try{
            
            ClienteController clienteController = new ClienteController();
            
            ClienteClasse update = clienteController.update(this.clientes);
      
            
            
            if(this.clientes == update){
             JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso!");
             this.clientes = update;
             this.atualizaTela(evt);
            
            }
            
            
        }catch(Exception e){
            
            
            return;
        
    }
    }//GEN-LAST:event_clienteEditSaveActionPerformed

    private void clienteNomeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteNomeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteNomeEditActionPerformed

    private void ClienteEmailEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteEmailEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteEmailEditActionPerformed

    private void clienteTelefoneEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTelefoneEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTelefoneEditActionPerformed

    private void clienteCepEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCepEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteCepEditActionPerformed

    private void clienteEnderecoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEnderecoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteEnderecoEditActionPerformed

    private void clienteCpfEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCpfEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteCpfEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FornecedoresEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ClienteEmailEdit;
    private javax.swing.JLabel cepEditLabel;
    private javax.swing.JFormattedTextField clienteCepEdit;
    private javax.swing.JLabel clienteCepEditLabel;
    private javax.swing.JFormattedTextField clienteCpfEdit;
    private javax.swing.JLabel clienteCpfEditLabel;
    private javax.swing.JButton clienteEditSave;
    private javax.swing.JFormattedTextField clienteEnderecoEdit;
    private javax.swing.JLabel clienteEnderecoEditLabel;
    private javax.swing.JFormattedTextField clienteNomeEdit;
    private javax.swing.JFormattedTextField clienteTelefoneEdit;
    private javax.swing.JLabel clienteTelefoneTelefoneLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nomeEditLabel;
    // End of variables declaration//GEN-END:variables
}
