/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import merc.Classes.ClienteClasse;
import merc.Classes.EnderecoClasse;
import merc.Classes.FornecedorClasse;
import merc.controller.ClienteController;
import merc.controller.EnderecoController;
import merc.controller.FornecedorController;

/**
 *
 * @author bsbru
 */
public class ClientesAdd extends javax.swing.JFrame {

    /**
     * Creates new form UsuariosAdd
     */
    public ClientesAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clienteCepAddLabel = new javax.swing.JLabel();
        clienteNomeAddLabel = new javax.swing.JLabel();
        clienteNomeAdd = new javax.swing.JFormattedTextField();
        clienteAddSave = new javax.swing.JButton();
        clienteEnderecoAdd = new javax.swing.JFormattedTextField();
        clienteEmailAddLabel1 = new javax.swing.JLabel();
        clienteEmailAdd = new javax.swing.JFormattedTextField();
        clienteCpfAddLabel2 = new javax.swing.JLabel();
        clienteCpfAdd = new javax.swing.JFormattedTextField();
        clienteTelefoneAddLabel3 = new javax.swing.JLabel();
        clienteTelefoneAdd = new javax.swing.JFormattedTextField();
        clienteEnderecoAddLabel4 = new javax.swing.JLabel();
        enderecoDescricaoAdd4 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        clienteCepAdd = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        jLabel1.setText("Novo Cliente");

        clienteCepAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteCepAddLabel.setText("CEP:");

        clienteNomeAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteNomeAddLabel.setText("Nome:");

        clienteNomeAdd.setToolTipText("");
        clienteNomeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteNomeAddActionPerformed(evt);
            }
        });

        clienteAddSave.setText("Salvar");
        clienteAddSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteAddSaveActionPerformed(evt);
            }
        });

        clienteEnderecoAdd.setToolTipText("");
        clienteEnderecoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEnderecoAddActionPerformed(evt);
            }
        });

        clienteEmailAddLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteEmailAddLabel1.setText("Email:");

        clienteEmailAdd.setToolTipText("");
        clienteEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEmailAddActionPerformed(evt);
            }
        });

        clienteCpfAddLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteCpfAddLabel2.setText("CPF:");

        clienteCpfAdd.setToolTipText("");
        clienteCpfAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCpfAddActionPerformed(evt);
            }
        });

        clienteTelefoneAddLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteTelefoneAddLabel3.setText("Telefone:");

        clienteTelefoneAdd.setToolTipText("");
        clienteTelefoneAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTelefoneAddActionPerformed(evt);
            }
        });

        clienteEnderecoAddLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clienteEnderecoAddLabel4.setText("Endereço:");

        enderecoDescricaoAdd4.setToolTipText("");
        enderecoDescricaoAdd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoDescricaoAdd4ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Endereço");

        clienteCepAdd.setToolTipText("");
        clienteCepAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCepAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(enderecoDescricaoAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(clienteAddSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clienteNomeAddLabel)
                                    .addComponent(clienteEmailAddLabel1)
                                    .addComponent(clienteTelefoneAddLabel3)
                                    .addComponent(clienteCpfAddLabel2)
                                    .addComponent(clienteEnderecoAddLabel4)
                                    .addComponent(clienteCepAddLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clienteNomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clienteEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clienteTelefoneAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clienteCpfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clienteEnderecoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clienteCepAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(131, 131, 131)))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteNomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteNomeAddLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteEmailAddLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clienteTelefoneAddLabel3)
                    .addComponent(clienteTelefoneAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteCpfAddLabel2)
                    .addComponent(clienteCpfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteEnderecoAddLabel4)
                    .addComponent(clienteEnderecoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteCepAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteCepAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clienteAddSave)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(enderecoDescricaoAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clienteNomeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteNomeAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteNomeAddActionPerformed

    private void clienteAddSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteAddSaveActionPerformed
        // TODO add your handling code here:
       if(clienteNomeAdd.getText().isEmpty() || clienteEnderecoAdd.getText().isEmpty() || clienteCpfAdd.getText().isEmpty() || clienteTelefoneAdd.getText().isEmpty() || clienteEmailAdd.getText().isEmpty() || clienteCepAdd.getText().isEmpty()){
            
           JOptionPane.showMessageDialog(null, "Dados incompletos!");
           return;
            
        }
        try{
            
            ClienteController clienteController = new ClienteController();
            
            boolean insert = clienteController.newCliente(clienteNomeAdd.getText(),clienteEmailAdd.getText(),clienteTelefoneAdd.getText(),clienteCpfAdd.getText(),clienteEnderecoAdd.getText(),clienteCepAdd.getText());
      
            
            if(insert == false){
                 JOptionPane.showMessageDialog(null, "Erro ao inserir os dados!");
            }
            
            if(insert == true){
             JOptionPane.showMessageDialog(null, "Cliente inserido com sucesso!");
             this.limpaTela(evt);
             

 
            }
            
            
        }catch(Exception e){
            
            return;
        
    }
    }//GEN-LAST:event_clienteAddSaveActionPerformed
 
    private void limpaTela(java.awt.event.ActionEvent evt){
        
        clienteNomeAdd.setText("");
        clienteEnderecoAdd.setText("");
        clienteCpfAdd.setText("");
        clienteCepAdd.setText("");
        clienteEmailAdd.setText("");
        clienteTelefoneAdd.setText("");
                  
        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        this.dispose();
        
        
       ClienteController clienteController = new ClienteController();
        ArrayList<ClienteClasse> carregaClientes = clienteController.select();



        Clientes clientes = new Clientes(carregaClientes);
        clientes.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Clientes.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void clienteEnderecoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEnderecoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteEnderecoAddActionPerformed

    private void clienteEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteEmailAddActionPerformed

    private void clienteCpfAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCpfAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteCpfAddActionPerformed

    private void clienteTelefoneAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTelefoneAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTelefoneAddActionPerformed

    private void enderecoDescricaoAdd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoDescricaoAdd4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoDescricaoAdd4ActionPerformed

    private void clienteCepAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCepAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteCepAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clienteAddSave;
    private javax.swing.JFormattedTextField clienteCepAdd;
    private javax.swing.JLabel clienteCepAddLabel;
    private javax.swing.JFormattedTextField clienteCpfAdd;
    private javax.swing.JLabel clienteCpfAddLabel2;
    private javax.swing.JFormattedTextField clienteEmailAdd;
    private javax.swing.JLabel clienteEmailAddLabel1;
    private javax.swing.JFormattedTextField clienteEnderecoAdd;
    private javax.swing.JLabel clienteEnderecoAddLabel4;
    private javax.swing.JFormattedTextField clienteNomeAdd;
    private javax.swing.JLabel clienteNomeAddLabel;
    private javax.swing.JFormattedTextField clienteTelefoneAdd;
    private javax.swing.JLabel clienteTelefoneAddLabel3;
    private javax.swing.JFormattedTextField enderecoDescricaoAdd4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
