/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import merc.Classes.CompraClasse;
import merc.Classes.FornecedorClasse;
import merc.Classes.ItemCompraClasse;
import merc.Classes.ProdutoClasse;
import merc.controller.FornecedorController;
import merc.controller.ItemCompraController;
import merc.controller.ProdutoController;

/**
 *
 * @author bsbru
 */
public class ComprasEdit extends javax.swing.JFrame {
    
    
   public  CompraClasse compras;

    /**
     * Creates new form UsuariosAdd
     */
    public ComprasEdit(CompraClasse compra) {
        initComponents();
        
        jdataCompraEdit.setText(compra.getData());
        compraFornecedorEdit.setText(compra.getNomeFornecedor());
        
        
        
        this.preencheTabela(this.carregaItems(compra));
  
        this.compras = compra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        produtoDescricaoEditLabel = new javax.swing.JLabel();
        produtoValorEditLabel = new javax.swing.JLabel();
        compraFornecedorEdit = new javax.swing.JFormattedTextField();
        produtoEditSave = new javax.swing.JButton();
        jdataCompraEdit = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jcompraItemsTable = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        jLabel1.setText("Alterar Compra");

        produtoDescricaoEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtoDescricaoEditLabel.setText("Data:");

        produtoValorEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtoValorEditLabel.setText("Fornecedor:");

        compraFornecedorEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        compraFornecedorEdit.setToolTipText("");
        compraFornecedorEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraFornecedorEditActionPerformed(evt);
            }
        });

        produtoEditSave.setText("Salvar");
        produtoEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoEditSaveActionPerformed(evt);
            }
        });

        jdataCompraEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jdataCompraEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdataCompraEditActionPerformed(evt);
            }
        });

        jcompraItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Cod Compra", "Produto", "Cod Produto", "Qtde", "Valor Total", "Valor Un"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jcompraItemsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(produtoEditSave)
                        .addGap(386, 386, 386))))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(produtoDescricaoEditLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdataCompraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(produtoValorEditLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compraFornecedorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdataCompraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(produtoDescricaoEditLabel)
                    .addComponent(produtoValorEditLabel)
                    .addComponent(compraFornecedorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(produtoEditSave)
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void compraFornecedorEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraFornecedorEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compraFornecedorEditActionPerformed

    private void produtoEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoEditSaveActionPerformed
        // TODO add your handling code here:
       if(produtoDescricaoEdit.getText().isEmpty()|| compraFornecedorEdit.getText().isEmpty() || produtoQuantidadeEdit.getText().isEmpty()){
            
           JOptionPane.showMessageDialog(null, "Dados incompletos!");
           return;
            
        }
       
        this.produtos.setDescricao(produtoDescricaoEdit.getText());
        this.produtos.setValor_unitario(Integer.parseInt(compraFornecedorEdit.getText()));
        this.produtos.setQtde_estoque(Integer.parseInt(produtoQuantidadeEdit.getText()));
     
        
 
        try{
            
           ProdutoController produtoController = new ProdutoController();
            
            ProdutoClasse update = produtoController.update(this.produtos);
      
            
            
            if(this.produtos == update){
             JOptionPane.showMessageDialog(null, "Produto alterado com sucesso!");
             this.produtos = update;
             this.atualizaTela(evt);
            
            }
            
            
        }catch(Exception e){
            
            
            return;
        
    }
    }//GEN-LAST:event_produtoEditSaveActionPerformed
 
    private void limpaTela(java.awt.event.ActionEvent evt){
        

//        compraFornecedorEdit.setText("");
        
    }
    
    public ArrayList<ItemCompraClasse> carregaItems(CompraClasse compra){
        
         ItemCompraController  itemCompraController = new ItemCompraController();
        ArrayList<ItemCompraClasse> carregaItems = itemCompraController.selectCompra(compra.getId());
        

        return carregaItems;
        
        
   
        
    }
    
        
    public boolean preencheTabela(ArrayList<ItemCompraClasse> itemsCompra){
            DefaultTableModel tableModel = (DefaultTableModel) jcompraItemsTable.getModel();
                tableModel.setRowCount(0);
                itemsCompra.forEach((item)->{
                    tableModel.addRow(new Object[] {
                        item.getId(),
                        item.getCompra_id(),
                        item.getNome_produto(),
                        item.getProduto_id(),
                        item.getQtde(),
                        item.getValor(),
                        item.getValorUn(),
                        
                        
                    });
                
            });
                jcompraItemsTable.setModel(tableModel);
                
                return true;
    }
    
    private void atualizaTela(java.awt.event.ActionEvent evt){
        
        produtoDescricaoEdit.setText(this.produtos.getDescricao());
        compraFornecedorEdit.setText(Integer.toString(this.produtos.getValor_unitario()));
        produtoQuantidadeEdit.setText(Integer.toString(this.produtos.getQtde_estoque()));
        
        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        this.dispose();
        
        
        ProdutoController produtosController = new ProdutoController();
        ArrayList<ProdutoClasse> carregaProdutos = produtosController.select();



        Produtos telaProdutos = new Produtos(carregaProdutos);
        telaProdutos.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Produtos.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jdataCompraEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdataCompraEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdataCompraEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FornecedoresEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField compraFornecedorEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jcompraItemsTable;
    private javax.swing.JFormattedTextField jdataCompraEdit;
    private javax.swing.JLabel produtoDescricaoEditLabel;
    private javax.swing.JButton produtoEditSave;
    private javax.swing.JLabel produtoValorEditLabel;
    // End of variables declaration//GEN-END:variables
}
