/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import merc.Classes.CompraClasse;
import merc.Classes.EnderecoClasse;
import merc.Classes.FornecedorClasse;
import merc.Classes.ProdutoClasse;
import merc.controller.CompraController;
import merc.controller.EnderecoController;
import merc.controller.FornecedorController;
import merc.controller.ProdutoController;

/**
 *
 * @author bsbru
 */
public class ComprasAdd extends javax.swing.JFrame {

    public FornecedorClasse fornecedores;

    /**
     * Creates new form UsuariosAdd
     */
    public ComprasAdd(FornecedorClasse fornecedor) {

        initComponents();

        String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());

        dataCompaAdd.setText(timeStamp);

        if (fornecedor.getId() > 0) {

            this.fornecedores = fornecedor;
            this.preencheFornecedor();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valorProdutoAddLabel = new javax.swing.JLabel();
        produtoDescricaoAddLabel = new javax.swing.JLabel();
        dataCompaAdd = new javax.swing.JFormattedTextField();
        produtoAddSave = new javax.swing.JButton();
        fornecedorCompraAdd = new javax.swing.JFormattedTextField();
        fornecedoresSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        jLabel1.setText("Nova Compra");

        valorProdutoAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        valorProdutoAddLabel.setText("Fornecedor:");

        produtoDescricaoAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtoDescricaoAddLabel.setText("Data:");

        dataCompaAdd.setToolTipText("");
        dataCompaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCompaAddActionPerformed(evt);
            }
        });

        produtoAddSave.setText("Salvar");
        produtoAddSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtoAddSaveMouseClicked(evt);
            }
        });

        fornecedorCompraAdd.setEditable(false);
        fornecedorCompraAdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        fornecedorCompraAdd.setToolTipText("");
        fornecedorCompraAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorCompraAddActionPerformed(evt);
            }
        });

        fornecedoresSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/alterar.png"))); // NOI18N
        fornecedoresSelect.setText("Selecionar");
        fornecedoresSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fornecedoresSelectMouseClicked(evt);
            }
        });
        fornecedoresSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedoresSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(produtoAddSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(produtoDescricaoAddLabel)
                            .addComponent(valorProdutoAddLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fornecedorCompraAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fornecedoresSelect))
                            .addComponent(dataCompaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtoDescricaoAddLabel)
                    .addComponent(dataCompaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorProdutoAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornecedorCompraAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornecedoresSelect))
                .addGap(118, 118, 118)
                .addComponent(produtoAddSave)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dataCompaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCompaAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCompaAddActionPerformed

    private void limpaTela(java.awt.event.ActionEvent evt) {

//        dataCompaAdd.setText("");
//        fornecedorCompraAdd.setText("");
//        quantidadeProdutoAdd.setText("");
    }

    private void preencheFornecedor() {

        fornecedorCompraAdd.setText(this.fornecedores.getNome());

    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

        this.dispose();

        CompraController compraController = new CompraController();
        ArrayList<CompraClasse> carregaCompras = compraController.select();

        Compras telaCompras = new Compras(carregaCompras);
        telaCompras.setVisible(true);


    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Compras.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void fornecedorCompraAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorCompraAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorCompraAddActionPerformed

    private void fornecedoresSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedoresSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedoresSelectActionPerformed

    private void fornecedoresSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fornecedoresSelectMouseClicked
        // TODO add your handling code here:

        FornecedorController forncedorController = new FornecedorController();
        ArrayList<FornecedorClasse> fornecedores = forncedorController.select();

        this.setVisible(false);
        FornecedoresLista fornecedoresLista = new FornecedoresLista(fornecedores);
        fornecedoresLista.setVisible(true);


    }//GEN-LAST:event_fornecedoresSelectMouseClicked

    private void produtoAddSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtoAddSaveMouseClicked
        // TODO add your handling code here:

        if (dataCompaAdd.getText().isEmpty() || fornecedorCompraAdd.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Dados incompletos!");
            return;

        }

        CompraController comprasController = new CompraController();
        Integer insert = comprasController.newCompra(dataCompaAdd.getText(), this.fornecedores.getId());

        JOptionPane.showMessageDialog(null, "Compra inserida com sucesso!");

        CompraController compraController = new CompraController();
        ArrayList<CompraClasse> carregaCompras = compraController.select();
        
        this.dispose();

//        Compras telaCompras = new Compras(carregaCompras);
//        telaCompras.setVisible(true);


    }//GEN-LAST:event_produtoAddSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprasAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprasAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprasAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprasAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ComprasAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField dataCompaAdd;
    private javax.swing.JFormattedTextField fornecedorCompraAdd;
    private javax.swing.JButton fornecedoresSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton produtoAddSave;
    private javax.swing.JLabel produtoDescricaoAddLabel;
    private javax.swing.JLabel valorProdutoAddLabel;
    // End of variables declaration//GEN-END:variables
}
