/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.DottedLineSeparator;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import merc.Classes.CompraClasse;
import merc.Classes.FornecedorClasse;
import merc.Classes.ProdutoClasse;
import merc.controller.CompraController;
import merc.controller.ProdutoController;



/**
 *
 * @author bsbru
 */
public class Compras extends javax.swing.JFrame {

    public  ArrayList<CompraClasse> compras;
    public Date dataInicioPicked;
    public Date dataFimPicked;
    /**
     * Creates new form Fornecedores
     */
    public Compras(ArrayList<CompraClasse> compras) {
        
        
        this.dispose();
        
        
    
        initComponents();
       
        
        this.compras = compras;
        
        this.preencheTabela();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        jDateComponentFactory1 = new org.jdatepicker.JDateComponentFactory();
        dateComponentFormatter2 = new org.jdatepicker.impl.DateComponentFormatter();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelFornecedores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCompras = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        comprasButtonAdd = new javax.swing.JButton();
        comprasButtonEdit = new javax.swing.JButton();
        comprasButtonDelete = new javax.swing.JButton();
        filtrarAction = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fornecedores");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/financeiro.png"))); // NOI18N
        jLabel1.setText("Compras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jTableCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Data", "Fornecedor", "Cod Fornecedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCompras.setToolTipText("");
        jTableCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCompras);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/reports.png"))); // NOI18N
        jButton2.setText("Gerar relatório");

        javax.swing.GroupLayout jPanelFornecedoresLayout = new javax.swing.GroupLayout(jPanelFornecedores);
        jPanelFornecedores.setLayout(jPanelFornecedoresLayout);
        jPanelFornecedoresLayout.setHorizontalGroup(
            jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelFornecedoresLayout.setVerticalGroup(
            jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
            .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        comprasButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        comprasButtonAdd.setText("Novo");
        comprasButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprasButtonAddMouseClicked(evt);
            }
        });
        comprasButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasButtonAddActionPerformed(evt);
            }
        });

        comprasButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        comprasButtonEdit.setText("Editar");
        comprasButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprasButtonEditMouseClicked(evt);
            }
        });
        comprasButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasButtonEditActionPerformed(evt);
            }
        });
        comprasButtonEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comprasButtonEditKeyTyped(evt);
            }
        });

        comprasButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/remover.png"))); // NOI18N
        comprasButtonDelete.setText("Excluir");
        comprasButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprasButtonDeleteMouseClicked(evt);
            }
        });
        comprasButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasButtonDeleteActionPerformed(evt);
            }
        });

        filtrarAction.setText("Filtrar");
        filtrarAction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filtrarActionMouseClicked(evt);
            }
        });
        filtrarAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarActionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("De:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Até:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Filtrar período");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/reports.png"))); // NOI18N
        jButton3.setText("Gerar relatório");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filtrarAction)
                        .addGap(18, 18, 18)
                        .addComponent(comprasButtonAdd)))
                .addGap(18, 18, 18)
                .addComponent(comprasButtonEdit)
                .addGap(18, 18, 18)
                .addComponent(comprasButtonDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addComponent(jLabel4)
                            .addComponent(filtrarAction)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comprasButtonEdit)
                            .addComponent(comprasButtonDelete)
                            .addComponent(comprasButtonAdd))))
                .addGap(18, 18, 18)
                .addComponent(jPanelFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comprasButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprasButtonAddActionPerformed

    private void comprasButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprasButtonAddMouseClicked
        // TODO add your handling code here:
        this.dispose();
        FornecedorClasse fornecedorClasse = new FornecedorClasse();
        fornecedorClasse.setId(0);
        ComprasAdd telaComprasAdd = new ComprasAdd(fornecedorClasse);
        telaComprasAdd.setVisible(true);
    }//GEN-LAST:event_comprasButtonAddMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jTableComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableComprasMouseClicked
        // TODO add your handling code here:
//        System.out.println(jTableFornecedores.getModel().getValueAt(jTableFornecedores.getSelectedRow(), 0));
    }//GEN-LAST:event_jTableComprasMouseClicked

    private void comprasButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprasButtonEditActionPerformed

    private void comprasButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprasButtonEditMouseClicked
        // TODO add your handling code here:
        
        
        if(jTableCompras.getSelectedRow() < 0){
            return;
            
        }
        
       
        
        Integer id = (Integer)jTableCompras.getModel().getValueAt(jTableCompras.getSelectedRow(), 0);
        String data = (String)jTableCompras.getModel().getValueAt(jTableCompras.getSelectedRow(), 1);
        String  fornecedor = (String)jTableCompras.getModel().getValueAt(jTableCompras.getSelectedRow(), 2);
        Integer cod_fornecedor = (Integer)jTableCompras.getModel().getValueAt(jTableCompras.getSelectedRow(), 3);
        
       CompraClasse compra = new CompraClasse();
       compra.setId(id);
       compra.setData(data);
       compra.setNomeFornecedor(fornecedor);
       compra.setFornecedor_id(cod_fornecedor);
    

        
        
        this.dispose();
        ComprasEdit telaCompraEdit = new ComprasEdit(compra);
        telaCompraEdit.setVisible(true);
        
    }//GEN-LAST:event_comprasButtonEditMouseClicked

    private void comprasButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprasButtonDeleteActionPerformed

    private void comprasButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprasButtonDeleteMouseClicked
        // TODO add your handling code here:
           if(jTableCompras.getSelectedRow() < 0){
            return;
            
        }
        
        Integer id = (Integer)jTableCompras.getModel().getValueAt(jTableCompras.getSelectedRow(), 0);

        
       CompraClasse compra = new CompraClasse();
       compra.setId(id);
       
       int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Você realmente deseja excluir o item selecionado?", "Confirmação", dialogButton);
       
       if(dialogResult == 0) {
           CompraController compraController = new CompraController();
           boolean remove = compraController.remove(compra);
           
           if(remove == true){
                JOptionPane.showMessageDialog(null, "Item removido com sucesso!");
                  this.dispose();
                  this.carregaTela();
           }else{
               JOptionPane.showMessageDialog(null, "Erro ao remover o item!");
           }
           
             } else {
               
                         } 
       
    }//GEN-LAST:event_comprasButtonDeleteMouseClicked

    private void comprasButtonEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comprasButtonEditKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_comprasButtonEditKeyTyped

    private void filtrarActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarActionActionPerformed
        // TODO add your handling code here:
        
        if(jDateChooser2.getDate() == null || jDateChooser1.getDate() == null ){
            return;
        }

        String dataInicioFormatada = new SimpleDateFormat("YYYY-MM-dd").format(jDateChooser2.getDate());
        String dataFimFormatada = new SimpleDateFormat("YYYY-MM-dd").format(jDateChooser1.getDate());
        
        this.dataInicioPicked = jDateChooser2.getDate();
        this.dataFimPicked = jDateChooser1.getDate();


        CompraController  compraController = new CompraController();
        ArrayList<CompraClasse> carregaCompras = compraController.selectFilter(dataInicioFormatada,dataFimFormatada);
        

         this.compras = carregaCompras;
         
         this.preencheTabela();

        
    }//GEN-LAST:event_filtrarActionActionPerformed

    private void filtrarActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtrarActionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrarActionMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        this.geraRelatorio();
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            
  
            public void run() {
     
            
                
                new Compras(compras).setVisible(true);

            }
        });
        
     
    }
    

    
    public boolean preencheTabela(){
            DefaultTableModel tableModel = (DefaultTableModel) jTableCompras.getModel();
                tableModel.setRowCount(0);
                compras.forEach((compra)->{
                    tableModel.addRow(new Object[] {
                        compra.getId(),
                        compra.getData(),
                        compra.getNomeFornecedor(),
                        compra.getFornecedor_id(),
                        
                    });
                
            });
                jTableCompras.setModel(tableModel);
                
                return true;
    }
    
        public void geraRelatorio() {

        Date dataName = new Date();
        String dataFormatadaFileName = new SimpleDateFormat("dd_MM_YY_HHmmss").format(dataName);

        Path path = FileSystems.getDefault().getPath("").toAbsolutePath();

        String fileName = "compras_" + dataFormatadaFileName + ".pdf";

        String dest = path + "/src/reports/" + fileName;

        File file = new File(dest);
        file.getParentFile().mkdirs();

        try {

            Date data = new Date();
            String dataFormatada = new SimpleDateFormat("dd-MM-YYYY HH:mm:ss").format(data);

            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(dest));
            document.open();

//            String dataString = data.toString();
            Chunk linebreak = new Chunk(new DottedLineSeparator());

 
            int totalItems = this.compras.size();
            
            Font f = new Font(Font.FontFamily.COURIER, 30.0f, Font.BOLD, BaseColor.BLACK);
            Paragraph tittle = new Paragraph("Relatório de Compras", f);
            tittle.setAlignment(Paragraph.ALIGN_CENTER);
            document.add(tittle);
            document.add(linebreak);

            document.add(new Paragraph("Gerado em " + dataFormatada));
            document.add(linebreak);
            
            document.add(new Paragraph("Total de items: " + totalItems));
            document.add(linebreak);

            if(this.dataFimPicked != null && this.dataInicioPicked != null){
                
           String dataInicioFormatada = new SimpleDateFormat("dd-MM-YYYY").format(this.dataInicioPicked);
           String dataFimFormatada = new SimpleDateFormat("dd-MM-YYYY").format(this.dataFimPicked);

                
            document.add(new Paragraph("Periodo: "+dataInicioFormatada+" a "+dataFimFormatada ));
            document.add(linebreak);
            }
        
            float columnWidth[] = {7, 15, 25,25};
            PdfPTable table = new PdfPTable(columnWidth);
            table.setWidthPercentage(100);

            table.addCell("ID");
            table.addCell("Data");
            table.addCell("Fornecedor");
            table.addCell("Cod Fornecedor");

            for (CompraClasse element : this.compras) {

                table.addCell(element.getId().toString());
                table.addCell(element.getData());
                table.addCell(element.getNomeFornecedor());
                table.addCell(element.getFornecedor_id().toString());

            }

            document.add(table);
            document.close();

            File myFile = new File(dest);
            Desktop.getDesktop().open(myFile);

        } catch (DocumentException de) {
            System.err.println(de.getMessage());
        } catch (FileNotFoundException e) {
        } catch (IOException e) {
        }
    }
    
    public void carregaTela(){
         CompraController  compraController = new CompraController();
        ArrayList<CompraClasse> carregaCompras = compraController.select();
        

        
        
        Compras telaCompras = new Compras(carregaCompras);
        telaCompras.setVisible(true);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprasButtonAdd;
    private javax.swing.JButton comprasButtonDelete;
    private javax.swing.JButton comprasButtonEdit;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter2;
    private javax.swing.JButton filtrarAction;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFornecedores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCompras;
    // End of variables declaration//GEN-END:variables

    void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void getInstance() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
