/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import merc.Classes.CompraClasse;
import merc.Classes.FornecedorClasse;
import merc.Classes.ItemCompraClasse;
import merc.Classes.ProdutoClasse;
import merc.controller.FornecedorController;
import merc.controller.ItemCompraController;
import merc.controller.ProdutoController;

/**
 *
 * @author bsbru
 */
public class ComprasEdit_old extends javax.swing.JFrame {
    
    
   public  CompraClasse compras;

    /**
     * Creates new form UsuariosAdd
     */
    public ComprasEdit_old(CompraClasse compra) {
        initComponents();
        
        dataCompraEdit2.setText(compra.getData());
        compraFornecedorEdit2.setText(compra.getNomeFornecedor());
        
        
        
        this.preencheTabela(this.carregaItems(compra));
  
        this.compras = compra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        produtoDescricaoEditLabel = new javax.swing.JLabel();
        produtoValorEditLabel = new javax.swing.JLabel();
        compraFornecedorEdit2 = new javax.swing.JFormattedTextField();
        produtoEditSave = new javax.swing.JButton();
        dataCompraEdit2 = new javax.swing.JFormattedTextField();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        jLabel1.setText("Alterar Compra");

        produtoDescricaoEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtoDescricaoEditLabel.setText("Data:");

        produtoValorEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtoValorEditLabel.setText("Fornecedor:");

        compraFornecedorEdit2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        compraFornecedorEdit2.setToolTipText("");

        produtoEditSave.setText("Salvar");
        produtoEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoEditSaveActionPerformed(evt);
            }
        });

        dataCompraEdit2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addComponent(produtoEditSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(produtoDescricaoEditLabel)
                            .addComponent(produtoValorEditLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compraFornecedorEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataCompraEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(421, 421, 421))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(303, 303, 303))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtoValorEditLabel)
                    .addComponent(compraFornecedorEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataCompraEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(produtoDescricaoEditLabel))
                .addGap(206, 206, 206)
                .addComponent(produtoEditSave)
                .addGap(62, 62, 62))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void produtoEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoEditSaveActionPerformed
        // TODO add your handling code here:
       if(produtoDescricaoEdit.getText().isEmpty()|| compraFornecedorEdit2.getText().isEmpty() || produtoQuantidadeEdit.getText().isEmpty()){
            
           JOptionPane.showMessageDialog(null, "Dados incompletos!");
           return;
            
        }
       
        this.produtos.setDescricao(produtoDescricaoEdit.getText());
        this.produtos.setValor_unitario(Integer.parseInt(compraFornecedorEdit2.getText()));
        this.produtos.setQtde_estoque(Integer.parseInt(produtoQuantidadeEdit.getText()));
     
        
 
        try{
            
           ProdutoController produtoController = new ProdutoController();
            
            ProdutoClasse update = produtoController.update(this.produtos);
      
            
            
            if(this.produtos == update){
             JOptionPane.showMessageDialog(null, "Produto alterado com sucesso!");
             this.produtos = update;
             this.atualizaTela(evt);
            
            }
            
            
        }catch(Exception e){
            
            
            return;
        
    }
    }//GEN-LAST:event_produtoEditSaveActionPerformed
 
    private void limpaTela(java.awt.event.ActionEvent evt){
        

//        compraFornecedorEdit.setText("");
        
    }
    
    public ArrayList<ItemCompraClasse> carregaItems(CompraClasse compra){
        
         ItemCompraController  itemCompraController = new ItemCompraController();
        ArrayList<ItemCompraClasse> carregaItems = itemCompraController.selectCompra(compra.getId());
        

        return carregaItems;
        
        
   
        
    }
    
        
    public boolean preencheTabela(ArrayList<ItemCompraClasse> itemsCompra){
            DefaultTableModel tableModel = (DefaultTableModel) jcompraItemsTable.getModel();
                tableModel.setRowCount(0);
                itemsCompra.forEach((item)->{
                    tableModel.addRow(new Object[] {
                        item.getId(),
                        item.getCompra_id(),
                        item.getNome_produto(),
                        item.getProduto_id(),
                        item.getQtde(),
                        item.getValor(),
                        item.getValorUn(),
                        
                        
                    });
                
            });
                jcompraItemsTable.setModel(tableModel);
                
                return true;
    }
    
    private void atualizaTela(java.awt.event.ActionEvent evt){
        
//        produtoDescricaoEdit.setText(this.produtos.getDescricao());
//        compraFornecedorEdit.setText(Integer.toString(this.produtos.getValor_unitario()));
//        produtoQuantidadeEdit.setText(Integer.toString(this.produtos.getQtde_estoque()));
        
        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        
        this.dispose();
        
        
        ProdutoController produtosController = new ProdutoController();
        ArrayList<ProdutoClasse> carregaProdutos = produtosController.select();



        Produtos telaProdutos = new Produtos(carregaProdutos);
        telaProdutos.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Compras.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprasEdit_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprasEdit_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprasEdit_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprasEdit_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FornecedoresEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField compraFornecedorEdit2;
    private javax.swing.JFormattedTextField dataCompraEdit2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JLabel produtoDescricaoEditLabel;
    private javax.swing.JButton produtoEditSave;
    private javax.swing.JLabel produtoValorEditLabel;
    // End of variables declaration//GEN-END:variables
}
