/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import merc.Classes.EnderecoClasse;
import merc.Classes.FornecedorClasse;
import merc.controller.EnderecoController;
import merc.controller.FornecedorController;

/**
 *
 * @author bsbru
 */
public class EnderecosEdit extends javax.swing.JFrame {
    
    
   public  EnderecoClasse enderecos;

    /**
     * Creates new form UsuariosAdd
     */
    public EnderecosEdit(EnderecoClasse endereco) {
        initComponents();
        
        enderecoDescricaoEdit.setText(endereco.getDescricao());
        enderecoCepEdit.setText(endereco.getCep());
        
        
        this.enderecos = endereco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        descricaoAddLabel = new javax.swing.JLabel();
        enderecoDescricaoEdit = new javax.swing.JFormattedTextField();
        descricaoCepAddLabel = new javax.swing.JLabel();
        enderecoCepEdit = new javax.swing.JFormattedTextField();
        enderecoEditSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        jLabel1.setText("Alterar Endereço");

        descricaoAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        descricaoAddLabel.setText("Descrição:");

        enderecoDescricaoEdit.setToolTipText("");
        enderecoDescricaoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoDescricaoEditActionPerformed(evt);
            }
        });

        descricaoCepAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        descricaoCepAddLabel.setText("CEP:");

        enderecoCepEdit.setToolTipText("");
        enderecoCepEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoCepEditActionPerformed(evt);
            }
        });

        enderecoEditSave.setText("Salvar");
        enderecoEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoEditSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descricaoCepAddLabel)
                            .addComponent(descricaoAddLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoDescricaoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enderecoCepEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(enderecoEditSave)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoDescricaoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoAddLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoCepAddLabel)
                    .addComponent(enderecoCepEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178)
                .addComponent(enderecoEditSave)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enderecoDescricaoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoDescricaoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoDescricaoEditActionPerformed

    private void enderecoCepEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoCepEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoCepEditActionPerformed
 
    private void limpaTela(java.awt.event.ActionEvent evt){
        
        enderecoDescricaoEdit.setText("");
        enderecoCepEdit.setText("");
        
    }
    
    private void atualizaTela(java.awt.event.ActionEvent evt){
        
        enderecoDescricaoEdit.setText(this.enderecos.getDescricao());
        enderecoCepEdit.setText(this.enderecos.getCep());

        
        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        this.dispose();
        
        
        EnderecoController enderecoController = new EnderecoController();
        ArrayList<EnderecoClasse> carregaEnderecos = enderecoController.select();



        Enderecos telaEndereco = new Enderecos(carregaEnderecos);
        telaEndereco.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Fornecedores.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void enderecoEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoEditSaveActionPerformed
        // TODO add your handling code here:

         if(enderecoDescricaoEdit.getText().isEmpty()|| enderecoCepEdit.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Dados incompletos!");
           return;
            
        }

        this.enderecos.setDescricao(enderecoDescricaoEdit.getText());
        this.enderecos.setCep(enderecoCepEdit.getText());  
       
 
        try{
            
            EnderecoController enderecoController = new EnderecoController();
            
            EnderecoClasse update = enderecoController.update(this.enderecos);
      
            
            
            if(this.enderecos == update){
             JOptionPane.showMessageDialog(null, "Endereço alterado com sucesso!");
             this.enderecos = update;
             this.atualizaTela(evt);
            
            }
            
            
        }catch(Exception e){
            
            
            return;
        
    }
    }//GEN-LAST:event_enderecoEditSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnderecosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnderecosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnderecosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnderecosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FornecedoresEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descricaoAddLabel;
    private javax.swing.JLabel descricaoCepAddLabel;
    private javax.swing.JFormattedTextField enderecoCepEdit;
    private javax.swing.JFormattedTextField enderecoDescricaoEdit;
    private javax.swing.JButton enderecoEditSave;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
