/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import merc.Classes.FornecedorClasse;
import merc.controller.FornecedorController;

/**
 *
 * @author bsbru
 */
public class FornecedoresAdd extends javax.swing.JFrame {

    /**
     * Creates new form UsuariosAdd
     */
    public FornecedoresAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userNameAddLabel = new javax.swing.JLabel();
        fornecedorNameAdd = new javax.swing.JFormattedTextField();
        userPassAddLabel = new javax.swing.JLabel();
        userStatusAddLabel = new javax.swing.JLabel();
        userEmailAddLabel = new javax.swing.JLabel();
        fornecedorEmailAdd = new javax.swing.JFormattedTextField();
        forncedorCnpjAdd = new javax.swing.JFormattedTextField();
        userAddSave = new javax.swing.JButton();
        fornecedorTelefoneAdd = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        jLabel1.setText("Novo Fornecedor");

        userNameAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userNameAddLabel.setText("Nome:");

        fornecedorNameAdd.setToolTipText("");
        fornecedorNameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorNameAddActionPerformed(evt);
            }
        });

        userPassAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userPassAddLabel.setText("Telefone:");

        userStatusAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userStatusAddLabel.setText("CNPJ");

        userEmailAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userEmailAddLabel.setText("Email:");

        fornecedorEmailAdd.setToolTipText("");
        fornecedorEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorEmailAddActionPerformed(evt);
            }
        });

        forncedorCnpjAdd.setToolTipText("");
        forncedorCnpjAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forncedorCnpjAddActionPerformed(evt);
            }
        });

        userAddSave.setText("Salvar");
        userAddSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAddSaveActionPerformed(evt);
            }
        });

        fornecedorTelefoneAdd.setToolTipText("");
        fornecedorTelefoneAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorTelefoneAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userPassAddLabel)
                                .addGap(18, 18, 18)
                                .addComponent(fornecedorTelefoneAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userStatusAddLabel)
                                .addGap(18, 18, 18)
                                .addComponent(forncedorCnpjAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNameAddLabel)
                                    .addComponent(userEmailAddLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fornecedorNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fornecedorEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(userAddSave)))
                .addGap(164, 222, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameAddLabel)
                    .addComponent(fornecedorNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userEmailAddLabel)
                    .addComponent(fornecedorEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPassAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornecedorTelefoneAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userStatusAddLabel)
                    .addComponent(forncedorCnpjAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(userAddSave)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fornecedorNameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorNameAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorNameAddActionPerformed

    private void fornecedorEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorEmailAddActionPerformed

    private void forncedorCnpjAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forncedorCnpjAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forncedorCnpjAddActionPerformed

    private void userAddSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAddSaveActionPerformed
        // TODO add your handling code here:
       if(fornecedorNameAdd.getText().isEmpty()|| fornecedorEmailAdd.getText().isEmpty() ||forncedorCnpjAdd.getText().isEmpty() || fornecedorTelefoneAdd.getText().isEmpty()){
            
           JOptionPane.showMessageDialog(null, "Dados incompletos!");
           return;
            
        }
        try{
            
            FornecedorController fornecedorController = new FornecedorController();
            
            boolean insert = fornecedorController.newFornecedor(fornecedorNameAdd.getText(),fornecedorEmailAdd.getText(),forncedorCnpjAdd.getText(),fornecedorTelefoneAdd.getText());
      
            
            if(insert == false){
                 JOptionPane.showMessageDialog(null, "Erro ao inserir os dados!");
            }
            
            if(insert == true){
             JOptionPane.showMessageDialog(null, "Fornecedor inserido com sucesso!");
             this.limpaTela(evt);
             

 
            }
            
            
        }catch(Exception e){
            
            return;
        
    }
    }//GEN-LAST:event_userAddSaveActionPerformed
 
    private void limpaTela(java.awt.event.ActionEvent evt){
        
        fornecedorNameAdd.setText("");
        fornecedorEmailAdd.setText("");
        forncedorCnpjAdd.setText("");
        fornecedorTelefoneAdd.setText("");
        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        this.dispose();
        
        
        FornecedorController fornecedoresController = new FornecedorController();
        ArrayList<FornecedorClasse> carregaUsuarios = fornecedoresController.select();



        Fornecedores telaFornecedor = new Fornecedores(carregaUsuarios);
        telaFornecedor.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Fornecedores.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void fornecedorTelefoneAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorTelefoneAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorTelefoneAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornecedoresAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornecedoresAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornecedoresAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedoresAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FornecedoresAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField forncedorCnpjAdd;
    private javax.swing.JFormattedTextField fornecedorEmailAdd;
    private javax.swing.JFormattedTextField fornecedorNameAdd;
    private javax.swing.JFormattedTextField fornecedorTelefoneAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton userAddSave;
    private javax.swing.JLabel userEmailAddLabel;
    private javax.swing.JLabel userNameAddLabel;
    private javax.swing.JLabel userPassAddLabel;
    private javax.swing.JLabel userStatusAddLabel;
    // End of variables declaration//GEN-END:variables
}
