/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import merc.Classes.FornecedorClasse;
import merc.controller.FornecedorController;

/**
 *
 * @author bsbru
 */
public class FornecedoresEdit extends javax.swing.JFrame {
    
    
   public  FornecedorClasse fornecedores;

    /**
     * Creates new form UsuariosAdd
     */
    public FornecedoresEdit(FornecedorClasse fornecedor) {
        initComponents();
        
        fornecedorNameEdit.setText(fornecedor.getNome());
        fornecedorEmailEdit.setText(fornecedor.getEmail());
        fornecedorCnpjEdit.setText(fornecedor.getCnpj());
        fornecedorTelefoneEdit.setText(fornecedor.getTelefone());
        
        this.fornecedores = fornecedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fornecedorNameAddLabel = new javax.swing.JLabel();
        fornecedorNameEdit = new javax.swing.JFormattedTextField();
        fornecedorTelefofoneEditLabel = new javax.swing.JLabel();
        fornecedorCnpjEditLabel = new javax.swing.JLabel();
        fornecedorEmailAddLabel = new javax.swing.JLabel();
        fornecedorEmailEdit = new javax.swing.JFormattedTextField();
        fornecedorCnpjEdit = new javax.swing.JFormattedTextField();
        fornecedorEditSave = new javax.swing.JButton();
        fornecedorTelefoneEdit = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        jLabel1.setText("Alterar Fornecedor");

        fornecedorNameAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fornecedorNameAddLabel.setText("Nome:");

        fornecedorNameEdit.setToolTipText("");
        fornecedorNameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorNameEditActionPerformed(evt);
            }
        });

        fornecedorTelefofoneEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fornecedorTelefofoneEditLabel.setText("Telefone:");

        fornecedorCnpjEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fornecedorCnpjEditLabel.setText("CNPJ:");

        fornecedorEmailAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fornecedorEmailAddLabel.setText("Email:");

        fornecedorEmailEdit.setToolTipText("");
        fornecedorEmailEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorEmailEditActionPerformed(evt);
            }
        });

        try {
            fornecedorCnpjEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fornecedorCnpjEdit.setToolTipText("");
        fornecedorCnpjEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorCnpjEditActionPerformed(evt);
            }
        });

        fornecedorEditSave.setText("Salvar");
        fornecedorEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorEditSaveActionPerformed(evt);
            }
        });

        try {
            fornecedorTelefoneEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fornecedorTelefoneEdit.setToolTipText("");
        fornecedorTelefoneEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorTelefoneEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fornecedorCnpjEditLabel)
                                .addGap(18, 18, 18)
                                .addComponent(fornecedorCnpjEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fornecedorEmailAddLabel)
                                    .addComponent(fornecedorTelefofoneEditLabel)
                                    .addComponent(fornecedorNameAddLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fornecedorTelefoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fornecedorNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fornecedorEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(fornecedorEditSave)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornecedorNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornecedorNameAddLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornecedorEmailAddLabel)
                    .addComponent(fornecedorEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornecedorTelefofoneEditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornecedorTelefoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornecedorCnpjEditLabel)
                    .addComponent(fornecedorCnpjEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(fornecedorEditSave)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fornecedorNameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorNameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorNameEditActionPerformed

    private void fornecedorEmailEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorEmailEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorEmailEditActionPerformed

    private void fornecedorCnpjEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorCnpjEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorCnpjEditActionPerformed

    private void fornecedorEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorEditSaveActionPerformed
        // TODO add your handling code here:
        
            if(this.limpaCampo(fornecedorCnpjEdit.getText()).isEmpty()){
             JOptionPane.showMessageDialog(null, "CNPJ não informado!");
             return;
        }
        
           if(this.limpaCampo(fornecedorTelefoneEdit.getText()).isEmpty()){
             JOptionPane.showMessageDialog(null, "Telefone não informado!");
             return;
        }
        
        
       if(fornecedorNameEdit.getText().isEmpty()|| fornecedorEmailEdit.getText().isEmpty() ||this.limpaCampo(fornecedorCnpjEdit.getText()).isEmpty() || this.limpaCampo(fornecedorTelefoneEdit.getText()).isEmpty()){
            
           JOptionPane.showMessageDialog(null, "Dados incompletos!");
           return;
            
        }
    
       
        this.fornecedores.setNome(fornecedorNameEdit.getText());
        this.fornecedores.setEmail(fornecedorEmailEdit.getText());
        this.fornecedores.setCnpj(fornecedorCnpjEdit.getText());
        this.fornecedores.setTelefone(fornecedorTelefoneEdit.getText());
        
 
        try{
            
            FornecedorController fornecedorController = new FornecedorController();
            
            FornecedorClasse update = fornecedorController.update(this.fornecedores);
      
            
            
            if(this.fornecedores == update){
             JOptionPane.showMessageDialog(null, "Fornecedor alterado com sucesso!");
             this.fornecedores = update;
             this.atualizaTela(evt);
            
            }
            
            
        }catch(Exception e){
            
            
            return;
        
    }
    }//GEN-LAST:event_fornecedorEditSaveActionPerformed
 
     
    private String limpaCampo(String campo){
        
      String campoLimpo = campo.replaceAll("[()\\-_\\.]", "");
      
      String retorno = "";
      
      
        for (int i = 0; i < campoLimpo.length(); i++) {
            if (campoLimpo.charAt(i) != ' ') {
                retorno = retorno + campoLimpo.charAt(i);
                
            }
              
            }
            
            
    
        return retorno;
        
    }
    
    private void limpaTela(java.awt.event.ActionEvent evt){
        
        fornecedorNameEdit.setText("");
        fornecedorEmailEdit.setText("");
        fornecedorCnpjEdit.setText("");
        fornecedorTelefoneEdit.setText("");
        
    }
    
    private void atualizaTela(java.awt.event.ActionEvent evt){
        
        fornecedorNameEdit.setText(this.fornecedores.getNome());
        fornecedorEmailEdit.setText(this.fornecedores.getEmail());
        fornecedorCnpjEdit.setText(this.fornecedores.getCnpj());
        fornecedorTelefoneEdit.setText(this.fornecedores.getTelefone());
        
        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        this.dispose();
        
        
        FornecedorController fornecedoresController = new FornecedorController();
        ArrayList<FornecedorClasse> carregaFornecedores = fornecedoresController.select();



        Fornecedores telaFornecedor = new Fornecedores(carregaFornecedores);
        telaFornecedor.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Fornecedores.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void fornecedorTelefoneEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorTelefoneEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorTelefoneEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornecedoresEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornecedoresEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornecedoresEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedoresEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FornecedoresEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField fornecedorCnpjEdit;
    private javax.swing.JLabel fornecedorCnpjEditLabel;
    private javax.swing.JButton fornecedorEditSave;
    private javax.swing.JLabel fornecedorEmailAddLabel;
    private javax.swing.JFormattedTextField fornecedorEmailEdit;
    private javax.swing.JLabel fornecedorNameAddLabel;
    private javax.swing.JFormattedTextField fornecedorNameEdit;
    private javax.swing.JLabel fornecedorTelefofoneEditLabel;
    private javax.swing.JFormattedTextField fornecedorTelefoneEdit;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
