/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import merc.Classes.CompraClasse;
import merc.Classes.EnderecoClasse;
import merc.Classes.FornecedorClasse;
import merc.Classes.ItemCompraClasse;
import merc.Classes.ProdutoClasse;
import merc.controller.EnderecoController;
import merc.controller.FornecedorController;
import merc.controller.ItemCompraController;
import merc.controller.ProdutoController;

/**
 *
 * @author bsbru
 */
public class itemCompraEdit extends javax.swing.JFrame {
    
    
   public  ItemCompraClasse itemsCompra;
   public  CompraClasse compras;

    /**
     * Creates new form UsuariosAdd
     */
    public itemCompraEdit(ItemCompraClasse itemCompra, CompraClasse compra) {
        initComponents();
        
         
        produtoItemCompraEdit.setText(itemCompra.getNome_produto());
        itemCompraCodEdit.setText(Integer.toString(itemCompra.getId()));
        quantidadeItemCompraEdit.setText(Integer.toString(itemCompra.getQtde()));
        
        this.compras = compra;
        this.itemsCompra = itemCompra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        produtoItemCompraEditLabel = new javax.swing.JLabel();
        itemCompraCodEdit = new javax.swing.JFormattedTextField();
        quantidadeItemCompraEditLabel = new javax.swing.JLabel();
        quantidadeItemCompraEdit = new javax.swing.JFormattedTextField();
        itemEditSave = new javax.swing.JButton();
        produtoItemCompraEdit = new javax.swing.JFormattedTextField();
        descricaoAddLabel1 = new javax.swing.JLabel();
        itemCompraItemEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        jLabel1.setText("Alterar item compra");

        produtoItemCompraEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtoItemCompraEditLabel.setText("Produto:");

        itemCompraCodEdit.setEditable(false);
        itemCompraCodEdit.setToolTipText("");
        itemCompraCodEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompraCodEditActionPerformed(evt);
            }
        });

        quantidadeItemCompraEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        quantidadeItemCompraEditLabel.setText("Quantidade:");

        quantidadeItemCompraEdit.setToolTipText("");
        quantidadeItemCompraEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeItemCompraEditActionPerformed(evt);
            }
        });

        itemEditSave.setText("Salvar");
        itemEditSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemEditSaveMouseClicked(evt);
            }
        });

        produtoItemCompraEdit.setEditable(false);
        produtoItemCompraEdit.setToolTipText("");
        produtoItemCompraEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoItemCompraEditActionPerformed(evt);
            }
        });

        descricaoAddLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descricaoAddLabel1.setText("Cod item:");

        itemCompraItemEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/alterar.png"))); // NOI18N
        itemCompraItemEdit.setText("Alterar item");
        itemCompraItemEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemCompraItemEditMouseClicked(evt);
            }
        });
        itemCompraItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompraItemEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(itemEditSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(quantidadeItemCompraEditLabel)
                                    .addComponent(produtoItemCompraEditLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantidadeItemCompraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(produtoItemCompraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(itemCompraItemEdit))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(descricaoAddLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(itemCompraCodEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoAddLabel1)
                    .addComponent(itemCompraCodEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtoItemCompraEditLabel)
                    .addComponent(produtoItemCompraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCompraItemEdit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeItemCompraEditLabel)
                    .addComponent(quantidadeItemCompraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125)
                .addComponent(itemEditSave)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemCompraCodEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompraCodEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCompraCodEditActionPerformed

    private void quantidadeItemCompraEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeItemCompraEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeItemCompraEditActionPerformed
 
    private void limpaTela(java.awt.event.ActionEvent evt){
//        
//        itemCompraCodEdit.setText("");
//        quantidadeItemCompraEdit.setText("");
        
    }
    
    private void atualizaTela(java.awt.event.ActionEvent evt){
        
//        itemCompraCodEdit.setText(this.enderecos.getDescricao());
//        quantidadeItemCompraEdit.setText(this.enderecos.getCep());

        
        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        this.dispose();
        
        
        EnderecoController enderecoController = new EnderecoController();
        ArrayList<EnderecoClasse> carregaEnderecos = enderecoController.select();



//        Enderecos telaEndereco = new Enderecos(carregaEnderecos);
//        telaEndereco.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
//        new Fornecedores.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void produtoItemCompraEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoItemCompraEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoItemCompraEditActionPerformed

    private void itemCompraItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompraItemEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCompraItemEditActionPerformed

    private void itemCompraItemEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemCompraItemEditMouseClicked
        // TODO add your handling code here:
        
        ProdutoController produtosControler =  new ProdutoController();
         ArrayList<ProdutoClasse> produtos = produtosControler.select();
        
        ItemsCompraLista itemCompraListaTela = new ItemsCompraLista( produtos,this.itemsCompra,this.compras);
        itemCompraListaTela.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_itemCompraItemEditMouseClicked

    private void itemEditSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemEditSaveMouseClicked
        // TODO add your handling code here:
        
        this.itemsCompra.setQtde(Integer.parseInt(quantidadeItemCompraEdit.getText()));
        
    
        
        ItemCompraController itemCompraController = new ItemCompraController();
        itemCompraController.update( this.itemsCompra);
        
        System.out.println(this.compras.getData());
        
        ComprasEdit comprasEditTela = new ComprasEdit(this.compras);        
        comprasEditTela.setVisible(true);
                
        
    }//GEN-LAST:event_itemEditSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itemCompraEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itemCompraEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itemCompraEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itemCompraEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FornecedoresEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descricaoAddLabel1;
    private javax.swing.JFormattedTextField itemCompraCodEdit;
    private javax.swing.JButton itemCompraItemEdit;
    private javax.swing.JButton itemEditSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField produtoItemCompraEdit;
    private javax.swing.JLabel produtoItemCompraEditLabel;
    private javax.swing.JFormattedTextField quantidadeItemCompraEdit;
    private javax.swing.JLabel quantidadeItemCompraEditLabel;
    // End of variables declaration//GEN-END:variables
}
