/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import merc.Classes.CompraClasse;
import merc.Classes.EnderecoClasse;
import merc.Classes.FornecedorClasse;
import merc.Classes.ItemCompraClasse;
import merc.Classes.ProdutoClasse;
import merc.controller.EnderecoController;
import merc.controller.FornecedorController;
import merc.controller.ItemCompraController;
import merc.controller.ProdutoController;

/**
 *
 * @author bsbru
 */
public class itemCompraAdd extends javax.swing.JFrame {
    
    
   public  ProdutoClasse produto;
   public CompraClasse compra;

    /**
     * Creates new form UsuariosAdd
     */
    public itemCompraAdd(ProdutoClasse produto,CompraClasse compra) {
        
        initComponents();
        
       
        this.produto = produto;
        this.compra = compra;
        
        produtoItemCompraAdd.setText(produto.getDescricao());
        
        
             if(produto.getId() != null){
                  itemCompraCodAdd.setText(Integer.toString(produto.getId()));
             }
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        produtoItemCompraEditLabel = new javax.swing.JLabel();
        itemCompraCodAdd = new javax.swing.JFormattedTextField();
        quantidadeItemCompraEditLabel = new javax.swing.JLabel();
        quantidadeItemCompraAdd = new javax.swing.JFormattedTextField();
        itemAddSave = new javax.swing.JButton();
        produtoItemCompraAdd = new javax.swing.JFormattedTextField();
        descricaoAddLabel1 = new javax.swing.JLabel();
        itemCompraItemAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        jLabel1.setText("Novo item");

        produtoItemCompraEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtoItemCompraEditLabel.setText("Produto:");

        itemCompraCodAdd.setEditable(false);
        itemCompraCodAdd.setToolTipText("");
        itemCompraCodAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompraCodAddActionPerformed(evt);
            }
        });

        quantidadeItemCompraEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        quantidadeItemCompraEditLabel.setText("Quantidade:");

        quantidadeItemCompraAdd.setToolTipText("");
        quantidadeItemCompraAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeItemCompraAddActionPerformed(evt);
            }
        });

        itemAddSave.setText("Salvar");
        itemAddSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAddSaveMouseClicked(evt);
            }
        });

        produtoItemCompraAdd.setEditable(false);
        produtoItemCompraAdd.setToolTipText("");
        produtoItemCompraAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoItemCompraAddActionPerformed(evt);
            }
        });

        descricaoAddLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descricaoAddLabel1.setText("Cod item:");

        itemCompraItemAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/alterar.png"))); // NOI18N
        itemCompraItemAdd.setText("Selecionar item");
        itemCompraItemAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemCompraItemAddMouseClicked(evt);
            }
        });
        itemCompraItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompraItemAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(276, 276, 276))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(quantidadeItemCompraEditLabel)
                                    .addComponent(produtoItemCompraEditLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantidadeItemCompraAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(produtoItemCompraAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(itemCompraItemAdd))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(descricaoAddLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemCompraCodAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(itemAddSave)
                        .addGap(336, 336, 336))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoAddLabel1)
                    .addComponent(itemCompraCodAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtoItemCompraEditLabel)
                    .addComponent(produtoItemCompraAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCompraItemAdd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeItemCompraEditLabel)
                    .addComponent(quantidadeItemCompraAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(itemAddSave)
                .addGap(120, 120, 120))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemCompraCodAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompraCodAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCompraCodAddActionPerformed

    private void quantidadeItemCompraAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeItemCompraAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeItemCompraAddActionPerformed
 
    private void limpaTela(java.awt.event.ActionEvent evt){
//        
//        itemCompraCodEdit.setText("");
//        quantidadeItemCompraEdit.setText("");
        
    }
    
    private void atualizaTela(java.awt.event.ActionEvent evt){
        
//        itemCompraCodEdit.setText(this.enderecos.getDescricao());
//        quantidadeItemCompraEdit.setText(this.enderecos.getCep());

        
        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        this.dispose();
        
        
        EnderecoController enderecoController = new EnderecoController();
        ArrayList<EnderecoClasse> carregaEnderecos = enderecoController.select();



//        Enderecos telaEndereco = new Enderecos(carregaEnderecos);
//        telaEndereco.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
//        new Fornecedores.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void produtoItemCompraAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoItemCompraAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoItemCompraAddActionPerformed

    private void itemCompraItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompraItemAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCompraItemAddActionPerformed

    private void itemCompraItemAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemCompraItemAddMouseClicked
        // TODO add your handling code here:
        
        ProdutoController produtosControler =  new ProdutoController();
         ArrayList<ProdutoClasse> produtos = produtosControler.select();
        
        ItemsCompraListaAdd itemCompraListaTela = new ItemsCompraListaAdd( produtos,this.compra);
        itemCompraListaTela.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_itemCompraItemAddMouseClicked

    private void itemAddSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddSaveMouseClicked
        // TODO add your handling code here:
     
        Integer quantidade  = Integer.parseInt(quantidadeItemCompraAdd.getText());

        
        ItemCompraController itemCompraController = new ItemCompraController();
        itemCompraController.newItemCompra(this.compra.getId(),this.produto.getId(),quantidade,this.produto.getValor_unitario());
        
        
    
             JOptionPane.showMessageDialog(null, "Item inserido com sucesso!");
             
            ProdutoController produtoController = new ProdutoController();
            produtoController.decrementaQuantidade(produto, quantidade);
             
              this.dispose();
             
              
         

        
  
        ComprasEdit comprasEditTela = new ComprasEdit(this.compra);        
        comprasEditTela.setVisible(true);
                
                
        
    }//GEN-LAST:event_itemAddSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itemCompraAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itemCompraAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itemCompraAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itemCompraAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FornecedoresEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descricaoAddLabel1;
    private javax.swing.JButton itemAddSave;
    private javax.swing.JFormattedTextField itemCompraCodAdd;
    private javax.swing.JButton itemCompraItemAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField produtoItemCompraAdd;
    private javax.swing.JLabel produtoItemCompraEditLabel;
    private javax.swing.JFormattedTextField quantidadeItemCompraAdd;
    private javax.swing.JLabel quantidadeItemCompraEditLabel;
    // End of variables declaration//GEN-END:variables
}
