/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import merc.Classes.EnderecoClasse;
import merc.Classes.FornecedorClasse;
import merc.controller.EnderecoController;
import merc.controller.FornecedorController;

/**
 *
 * @author bsbru
 */
public class ProdutosAdd extends javax.swing.JFrame {

    /**
     * Creates new form UsuariosAdd
     */
    public ProdutosAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valorProdutoAddLabel = new javax.swing.JLabel();
        produtoDescricaoAddLabel = new javax.swing.JLabel();
        produtoDescricaoAdd = new javax.swing.JFormattedTextField();
        produtoAddSave = new javax.swing.JButton();
        valorProdutoAdd = new javax.swing.JFormattedTextField();
        quantidadeProdutoAddLabel = new javax.swing.JLabel();
        quantidadeProdutoAdd = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        jLabel1.setText("Novo Produto");

        valorProdutoAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        valorProdutoAddLabel.setText("Valor Unitario:");

        produtoDescricaoAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtoDescricaoAddLabel.setText("Descrição:");

        produtoDescricaoAdd.setToolTipText("");
        produtoDescricaoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoDescricaoAddActionPerformed(evt);
            }
        });

        produtoAddSave.setText("Salvar");
        produtoAddSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoAddSaveActionPerformed(evt);
            }
        });

        valorProdutoAdd.setToolTipText("");
        valorProdutoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorProdutoAddActionPerformed(evt);
            }
        });

        quantidadeProdutoAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        quantidadeProdutoAddLabel.setText("Quantidade Estoque:");

        quantidadeProdutoAdd.setToolTipText("");
        quantidadeProdutoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeProdutoAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(produtoAddSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quantidadeProdutoAddLabel)
                            .addComponent(produtoDescricaoAddLabel)
                            .addComponent(valorProdutoAddLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(produtoDescricaoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(quantidadeProdutoAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addComponent(valorProdutoAdd, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtoDescricaoAddLabel)
                    .addComponent(produtoDescricaoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorProdutoAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorProdutoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeProdutoAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidadeProdutoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(produtoAddSave)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void produtoDescricaoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoDescricaoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoDescricaoAddActionPerformed

    private void produtoAddSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoAddSaveActionPerformed
        // TODO add your handling code here:
       if(produtoDescricaoAdd.getText().isEmpty() || valorProdutoAdd.getText().isEmpty()){
            
           JOptionPane.showMessageDialog(null, "Dados incompletos!");
           return;
            
        }
        try{
            
            EnderecoController enderecoController = new EnderecoController();
            
            Integer insert = enderecoController.newEndereco(produtoDescricaoAdd.getText(),valorProdutoAdd.getText());
      
            
            if(insert <=0){
                 JOptionPane.showMessageDialog(null, "Erro ao inserir os dados!");
            }
            
            if(insert > 0){
             JOptionPane.showMessageDialog(null, "Endereço inserido com sucesso!");
             this.limpaTela(evt);
             

 
            }
            
            
        }catch(Exception e){
            
            return;
        
    }
    }//GEN-LAST:event_produtoAddSaveActionPerformed
 
    private void limpaTela(java.awt.event.ActionEvent evt){
        
        produtoDescricaoAdd.setText("");
        valorProdutoAdd.setText("");
        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        this.dispose();
        
        
        EnderecoController enderecoController = new EnderecoController();
        ArrayList<EnderecoClasse> carregaEnderecos = enderecoController.select();



        Enderecos enderecoFornecedor = new Enderecos(carregaEnderecos);
        enderecoFornecedor.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Enderecos.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void valorProdutoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorProdutoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorProdutoAddActionPerformed

    private void quantidadeProdutoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeProdutoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeProdutoAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutosAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton produtoAddSave;
    private javax.swing.JFormattedTextField produtoDescricaoAdd;
    private javax.swing.JLabel produtoDescricaoAddLabel;
    private javax.swing.JFormattedTextField quantidadeProdutoAdd;
    private javax.swing.JLabel quantidadeProdutoAddLabel;
    private javax.swing.JFormattedTextField valorProdutoAdd;
    private javax.swing.JLabel valorProdutoAddLabel;
    // End of variables declaration//GEN-END:variables
}
