/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import merc.Classes.FornecedorClasse;
import merc.controller.FornecedorController;

/**
 *
 * @author bsbru
 */
public class ProdutosEdit extends javax.swing.JFrame {
    
    
   public  FornecedorClasse fornecedores;

    /**
     * Creates new form UsuariosAdd
     */
    public ProdutosEdit(FornecedorClasse fornecedor) {
        initComponents();
        
        produtoDescricaoEdit.setText(fornecedor.getNome());
        produtoValorEdit.setText(fornecedor.getEmail());
        fornecedorCnpjEdit.setText(fornecedor.getCnpj());
        produtoQuantidadeEdit.setText(fornecedor.getTelefone());
        
        this.fornecedores = fornecedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        produtoDescricaoEditLabel = new javax.swing.JLabel();
        produtoDescricaoEdit = new javax.swing.JFormattedTextField();
        produtoQuantidadeEditLabel = new javax.swing.JLabel();
        produtoValorEditLabel = new javax.swing.JLabel();
        produtoValorEdit = new javax.swing.JFormattedTextField();
        produtoEditSave = new javax.swing.JButton();
        produtoQuantidadeEdit = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        jLabel1.setText("Alterar Produto");

        produtoDescricaoEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtoDescricaoEditLabel.setText("Descrição:");

        produtoDescricaoEdit.setToolTipText("");
        produtoDescricaoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoDescricaoEditActionPerformed(evt);
            }
        });

        produtoQuantidadeEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtoQuantidadeEditLabel.setText("Quantidade estoque:");

        produtoValorEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        produtoValorEditLabel.setText("Valor unitário:");

        produtoValorEdit.setToolTipText("");
        produtoValorEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoValorEditActionPerformed(evt);
            }
        });

        produtoEditSave.setText("Salvar");
        produtoEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoEditSaveActionPerformed(evt);
            }
        });

        produtoQuantidadeEdit.setToolTipText("");
        produtoQuantidadeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoQuantidadeEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(produtoValorEditLabel)
                            .addComponent(produtoQuantidadeEditLabel)
                            .addComponent(produtoDescricaoEditLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(produtoDescricaoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(produtoQuantidadeEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addComponent(produtoValorEdit, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(produtoEditSave)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtoDescricaoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(produtoDescricaoEditLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtoValorEditLabel)
                    .addComponent(produtoValorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtoQuantidadeEditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(produtoQuantidadeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128)
                .addComponent(produtoEditSave)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void produtoDescricaoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoDescricaoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoDescricaoEditActionPerformed

    private void produtoValorEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoValorEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoValorEditActionPerformed

    private void produtoEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoEditSaveActionPerformed
        // TODO add your handling code here:
       if(produtoDescricaoEdit.getText().isEmpty()|| produtoValorEdit.getText().isEmpty() ||fornecedorCnpjEdit.getText().isEmpty() || produtoQuantidadeEdit.getText().isEmpty()){
            
           JOptionPane.showMessageDialog(null, "Dados incompletos!");
           return;
            
        }
       
        this.fornecedores.setNome(produtoDescricaoEdit.getText());
        this.fornecedores.setEmail(produtoValorEdit.getText());
        this.fornecedores.setCnpj(fornecedorCnpjEdit.getText());
        this.fornecedores.setTelefone(produtoQuantidadeEdit.getText());
        
 
        try{
            
            FornecedorController fornecedorController = new FornecedorController();
            
            FornecedorClasse update = fornecedorController.update(this.fornecedores);
      
            
            
            if(this.fornecedores == update){
             JOptionPane.showMessageDialog(null, "Fornecedor alterado com sucesso!");
             this.fornecedores = update;
             this.atualizaTela(evt);
            
            }
            
            
        }catch(Exception e){
            
            
            return;
        
    }
    }//GEN-LAST:event_produtoEditSaveActionPerformed
 
    private void limpaTela(java.awt.event.ActionEvent evt){
        
        produtoDescricaoEdit.setText("");
        produtoValorEdit.setText("");
        fornecedorCnpjEdit.setText("");
        produtoQuantidadeEdit.setText("");
        
    }
    
    private void atualizaTela(java.awt.event.ActionEvent evt){
        
        produtoDescricaoEdit.setText(this.fornecedores.getNome());
        produtoValorEdit.setText(this.fornecedores.getEmail());
        fornecedorCnpjEdit.setText(this.fornecedores.getCnpj());
        produtoQuantidadeEdit.setText(this.fornecedores.getTelefone());
        
        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        this.dispose();
        
        
        FornecedorController fornecedoresController = new FornecedorController();
        ArrayList<FornecedorClasse> carregaFornecedores = fornecedoresController.select();



        Fornecedores telaFornecedor = new Fornecedores(carregaFornecedores);
        telaFornecedor.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Fornecedores.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void produtoQuantidadeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoQuantidadeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoQuantidadeEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FornecedoresEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField produtoDescricaoEdit;
    private javax.swing.JLabel produtoDescricaoEditLabel;
    private javax.swing.JButton produtoEditSave;
    private javax.swing.JFormattedTextField produtoQuantidadeEdit;
    private javax.swing.JLabel produtoQuantidadeEditLabel;
    private javax.swing.JFormattedTextField produtoValorEdit;
    private javax.swing.JLabel produtoValorEditLabel;
    // End of variables declaration//GEN-END:variables
}
