/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import merc.Classes.FornecedorClasse;
import merc.Classes.UsuarioClasse;
import merc.controller.FornecedorController;
import merc.controller.UsuarioController;

/**
 *
 * @author bsbru
 */
public class UsuariosEdit extends javax.swing.JFrame {
    
    
   public  UsuarioClasse usuarios;

    /**
     * Creates new form UsuariosAdd
     */
    public UsuariosEdit(UsuarioClasse usuario) {
        initComponents();
        
        usuarioNameEdit.setText(usuario.getNome());
        usuarioEmailEdit.setText(usuario.getEmail());
        boxSituacaoUserEdit.setSelectedItem(usuario.getSituacao());
        
        this.usuarios = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fornecedorNameAddLabel = new javax.swing.JLabel();
        usuarioNameEdit = new javax.swing.JFormattedTextField();
        fornecedorTelefofoneEditLabel = new javax.swing.JLabel();
        fornecedorEmailAddLabel = new javax.swing.JLabel();
        usuarioEmailEdit = new javax.swing.JFormattedTextField();
        usuarioEditSave = new javax.swing.JButton();
        usuarioSenhaEdit = new javax.swing.JFormattedTextField();
        userStatusAddLabel = new javax.swing.JLabel();
        boxSituacaoUserEdit = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        jLabel1.setText("Alterar Usuario");

        fornecedorNameAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fornecedorNameAddLabel.setText("Nome:");

        usuarioNameEdit.setToolTipText("");
        usuarioNameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioNameEditActionPerformed(evt);
            }
        });

        fornecedorTelefofoneEditLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fornecedorTelefofoneEditLabel.setText("Senha:");

        fornecedorEmailAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fornecedorEmailAddLabel.setText("Email:");

        usuarioEmailEdit.setToolTipText("");
        usuarioEmailEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioEmailEditActionPerformed(evt);
            }
        });

        usuarioEditSave.setText("Salvar");
        usuarioEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioEditSaveActionPerformed(evt);
            }
        });

        usuarioSenhaEdit.setToolTipText("");
        usuarioSenhaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioSenhaEditActionPerformed(evt);
            }
        });

        userStatusAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userStatusAddLabel.setText("Situação:");

        boxSituacaoUserEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        boxSituacaoUserEdit.setToolTipText("");
        boxSituacaoUserEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSituacaoUserEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fornecedorEmailAddLabel)
                                    .addComponent(fornecedorTelefofoneEditLabel)
                                    .addComponent(fornecedorNameAddLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usuarioSenhaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usuarioNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usuarioEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userStatusAddLabel)
                                .addGap(18, 18, 18)
                                .addComponent(boxSituacaoUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(usuarioEditSave)
                        .addGap(328, 328, 328))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornecedorNameAddLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornecedorEmailAddLabel)
                    .addComponent(usuarioEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornecedorTelefofoneEditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioSenhaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userStatusAddLabel)
                    .addComponent(boxSituacaoUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(usuarioEditSave)
                .addGap(99, 99, 99))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioNameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioNameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioNameEditActionPerformed

    private void usuarioEmailEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioEmailEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioEmailEditActionPerformed

    private void usuarioEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioEditSaveActionPerformed
        // TODO add your handling code here:
        
        
       if(usuarioNameEdit.getText().isEmpty()|| usuarioEmailEdit.getText().isEmpty() || usuarioSenhaEdit.getText().isEmpty()){
            
           JOptionPane.showMessageDialog(null, "Dados incompletos!");
           return;
            
        }
  
       
        this.usuarios.setNome(usuarioNameEdit.getText());
        this.usuarios.setEmail(usuarioEmailEdit.getText());
        this.usuarios.setSenha(usuarioSenhaEdit.getText());
        this.usuarios.setSituacao(boxSituacaoUserEdit.getSelectedItem().toString());
        
       
 
        try{
            
            UsuarioController usuarioController = new UsuarioController();
            
            UsuarioClasse update = usuarioController.update(this.usuarios);
      
            
            
            if(this.usuarios == update){
             JOptionPane.showMessageDialog(null, "Usuario alterado com sucesso!");
             this.usuarios = update;
             this.atualizaTela(evt);
            
            }
            
            
        }catch(Exception e){
            
            
            return;
        
    }
    }//GEN-LAST:event_usuarioEditSaveActionPerformed
 
     
    private String limpaCampo(String campo){
        
      String campoLimpo = campo.replaceAll("[()\\-_\\.]", "");
      
      String retorno = "";
      
      
        for (int i = 0; i < campoLimpo.length(); i++) {
            if (campoLimpo.charAt(i) != ' ') {
                retorno = retorno + campoLimpo.charAt(i);
                
            }
              
            }
            
            
    
        return retorno;
        
    }
    
    private void limpaTela(java.awt.event.ActionEvent evt){
        
        usuarioNameEdit.setText("");
        usuarioEmailEdit.setText("");
        usuarioSenhaEdit.setText("");
        
    }
    
    private void atualizaTela(java.awt.event.ActionEvent evt){
        
        usuarioNameEdit.setText(this.usuarios.getNome());
        usuarioEmailEdit.setText(this.usuarios.getEmail());
        boxSituacaoUserEdit.setSelectedItem(this.usuarios.getSituacao());

        
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


        this.dispose();
        
        
        UsuarioController usuariosController = new UsuarioController();
        ArrayList<UsuarioClasse> carregaUsuarios = usuariosController.select();



        Usuarios telaUsuarios = new Usuarios(carregaUsuarios);
        telaUsuarios.setVisible(true);

        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Usuarios.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void usuarioSenhaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioSenhaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioSenhaEditActionPerformed

    private void boxSituacaoUserEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSituacaoUserEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSituacaoUserEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FornecedoresEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxSituacaoUserEdit;
    private javax.swing.JLabel fornecedorEmailAddLabel;
    private javax.swing.JLabel fornecedorNameAddLabel;
    private javax.swing.JLabel fornecedorTelefofoneEditLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel userStatusAddLabel;
    private javax.swing.JButton usuarioEditSave;
    private javax.swing.JFormattedTextField usuarioEmailEdit;
    private javax.swing.JFormattedTextField usuarioNameEdit;
    private javax.swing.JFormattedTextField usuarioSenhaEdit;
    // End of variables declaration//GEN-END:variables
}
