/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merc.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import merc.Classes.UsuarioClasse;
import merc.controller.UsuarioController;

/**
 *
 * @author bsbru
 */
public class UsuariosAdd extends javax.swing.JFrame {

    /**
     * Creates new form UsuariosAdd
     */
    public UsuariosAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userNameAddLabel = new javax.swing.JLabel();
        userNameAdd = new javax.swing.JFormattedTextField();
        userPassAddLabel = new javax.swing.JLabel();
        userStatusAddLabel = new javax.swing.JLabel();
        userEmailAddLabel = new javax.swing.JLabel();
        userEmailAdd = new javax.swing.JFormattedTextField();
        userPassAdd = new javax.swing.JFormattedTextField();
        userAddSave = new javax.swing.JButton();
        boxSituacaoUserAdd = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        jLabel1.setText("Novo usuário");

        userNameAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userNameAddLabel.setText("Nome:");

        userNameAdd.setToolTipText("");
        userNameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameAddActionPerformed(evt);
            }
        });

        userPassAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userPassAddLabel.setText("Senha:");

        userStatusAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userStatusAddLabel.setText("Situação:");

        userEmailAddLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userEmailAddLabel.setText("Email:");

        userEmailAdd.setToolTipText("");
        userEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailAddActionPerformed(evt);
            }
        });

        userPassAdd.setToolTipText("");
        userPassAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassAddActionPerformed(evt);
            }
        });

        userAddSave.setText("Salvar");
        userAddSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAddSaveActionPerformed(evt);
            }
        });

        boxSituacaoUserAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        boxSituacaoUserAdd.setToolTipText("");
        boxSituacaoUserAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSituacaoUserAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userPassAddLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userPassAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userStatusAddLabel)
                                .addGap(18, 18, 18)
                                .addComponent(boxSituacaoUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNameAddLabel)
                                    .addComponent(userEmailAddLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(userAddSave)
                        .addGap(344, 344, 344))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameAddLabel)
                    .addComponent(userNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userEmailAddLabel)
                    .addComponent(userEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPassAddLabel)
                    .addComponent(userPassAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userStatusAddLabel)
                    .addComponent(boxSituacaoUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(userAddSave)
                .addGap(102, 102, 102))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userNameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameAddActionPerformed

    private void userEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEmailAddActionPerformed

    private void userPassAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassAddActionPerformed

    private void userAddSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAddSaveActionPerformed
        // TODO add your handling code here:
       if(userNameAdd.getText().isEmpty()|| userEmailAdd.getText().isEmpty() ||userPassAdd.getText().isEmpty() ||boxSituacaoUserAdd.getSelectedItem().toString().isEmpty()){
            
           JOptionPane.showMessageDialog(null, "Dados incompletos!");
           return;
            
        }
        try{
            
            UsuarioController usuarioController = new UsuarioController();
            
            boolean insert = usuarioController.newUser(userNameAdd.getText(),userEmailAdd.getText(),userPassAdd.getText(),boxSituacaoUserAdd.getSelectedItem().toString());
      
            
            if(insert == false){
                 JOptionPane.showMessageDialog(null, "Erro ao inserir os dados!");
            }
            
            if(insert == true){
             JOptionPane.showMessageDialog(null, "Usuário inserido com sucesso!");
             this.limpaTela(evt);
             

 
            }
            
            
        }catch(Exception e){
            
            return;
        
    }
    }//GEN-LAST:event_userAddSaveActionPerformed
 
    private void limpaTela(java.awt.event.ActionEvent evt){
        
        userNameAdd.setText("");
        userEmailAdd.setText("");
        userPassAdd.setText("");
        boxSituacaoUserAdd.setSelectedIndex(0);
        
    }
    
    private void boxSituacaoUserAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSituacaoUserAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSituacaoUserAddActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        new UsuariosAdd().setVisible(false);

        this.dispose();
        
        
        UsuarioController  usuariosController = new UsuarioController();
        ArrayList<UsuarioClasse> carregaUsuarios = usuariosController.select();



        Usuarios telaUsuario = new Usuarios(carregaUsuarios);
        telaUsuario.setVisible(true);
//        telaUsuario.dispose();
        
//        new Usuarios.setVisible(true);
        
        
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        new Usuarios.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuariosAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxSituacaoUserAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton userAddSave;
    private javax.swing.JFormattedTextField userEmailAdd;
    private javax.swing.JLabel userEmailAddLabel;
    private javax.swing.JFormattedTextField userNameAdd;
    private javax.swing.JLabel userNameAddLabel;
    private javax.swing.JFormattedTextField userPassAdd;
    private javax.swing.JLabel userPassAddLabel;
    private javax.swing.JLabel userStatusAddLabel;
    // End of variables declaration//GEN-END:variables
}
